## Assignment Solutions 8

Question 1. Write a Python Program to Add Two Matrices?

In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[0,1,2]])

c= a+b
print("The addition of matrix is: ")
print(c)

The addition of matrix is: 
[[ 8 10 12]
 [ 4  6  8]]


Question 2. Write a Python Program to Multiply Two Matrices?

In [4]:
a = np.array([[1,2],[4,5]])
b = np.array([[7,8],[0,1]])
c = a.dot(b)
print("The multiplication of matrix is: ")
print(c)

The multiplication of matrix is: 
[[ 7 10]
 [28 37]]


Question 3. Write a Python Program to Transpose a Matrix?

In [6]:
a = np.array([[1,2,3],
              [4,5,6]])
at=a.transpose()
print("The transpose of the matrix is: ")
print(at)

The transpose of the matrix is: 
[[1 4]
 [2 5]
 [3 6]]


Question 4. Write a Python Program to Sort Words in Alphabetic Order?

In [7]:
def sortstring():
    words = input("Enter a string: ").title()
    sorted_words = sorted(words.split(' '))
    print(' '.join(sorted_words))

sortstring()

Enter a string: I am a girl
A Am Girl I


Question 5. Write a Python Program to Remove Punctuation From a String?

In [8]:
def removePunctuations():
    punctuations = '''!()-[]{}:;"'\,<>./?@#$%^&*_~`'''
    st = input('Enter a string: ')
    out_st = ''
    for i in st:
        if i not in punctuations:
            out_st += i
    print(out_st)

removePunctuations()

NameError: name 'remove_punctuations' is not defined